# Generated by Django 4.0 on 2022-01-02 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='pin_code',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Invalid Indian pincode Detail!\nContact Us, if you have entered the correct Pincode Detail and still it didn't accept the given Input", regex='^[1-9]{1}[0-9]{5}$')]),
        ),
    ]
