# Generated by Django 3.2 on 2022-01-17 10:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_users_pin_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='mechanic_threshold',
            field=models.IntegerField(default=5),
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=30)),
                ('desc', models.TextField()),
                ('vehicle_type', models.CharField(choices=[('2 WHEELER', '2 WHEELER'), ('4 WHEELER', '4 WHEELER'), ('HEAVY VEHICLE', 'HEAVY VEHICLE')], max_length=15)),
                ('mechanic', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Add or Manage Service(s)',
            },
        ),
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_model', models.CharField(max_length=50, verbose_name='Model')),
                ('vehicle_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Invalid Number Plate Detail!\nContact Us, if you have entered the correct Number Plate Detail and sill it didn't accept the given Input", regex='^[A-Z]{2}[ -][0-9]{1,2}(?: [A-Z])?(?: [A-Z]*)? [0-9]{1,4}$')], verbose_name='number')),
                ('issues', models.TextField(blank=True, null=True, verbose_name='Describe Any Specific Issues')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Booked', 'Booked'), ('Under Service', 'Under Service'), ('Ready for delivery', 'Ready for delivery'), ('Completed', 'Completed')], default='Pending', max_length=50)),
                ('booked_date', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('service_date', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
                ('mechanic', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='mechanic', to=settings.AUTH_USER_MODEL)),
                ('service', smart_selects.db_fields.ChainedForeignKey(chained_field='mechanic', chained_model_field='mechanic', on_delete=django.db.models.deletion.CASCADE, to='core.services')),
            ],
            options={
                'verbose_name_plural': 'Add or Manage Customer Booking(s)',
            },
        ),
    ]
