# Generated by Django 3.2 on 2022-01-18 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220117_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='mechanic',
            field=models.ForeignKey(limit_choices_to=models.Q(groups__name='mechanics'), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
