# Generated by Django 3.2 on 2022-01-18 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_services_mechanic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='customer',
            field=models.ForeignKey(limit_choices_to=models.Q(groups__name='customers'), on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='mechanic',
            field=models.ForeignKey(limit_choices_to=models.Q(groups__name='mechanics'), on_delete=django.db.models.deletion.CASCADE, related_name='mechanic', to=settings.AUTH_USER_MODEL),
        ),
    ]
