# Generated by Django 3.2 on 2022-01-18 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220119_0122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicebooking',
            options={'verbose_name_plural': 'Service Booking(s)'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name_plural': 'Service(s)'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name_plural': 'User Detail'},
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='customer',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(groups__name='customers'), on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='services',
            name='mechanic',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(groups__name='mechanics'), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
