# Generated by Django 3.2 on 2022-01-18 21:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220119_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='service_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
