# Generated by Django 3.2 on 2022-02-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20220228_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expected Delivery Date'),
        ),
    ]
